### ISSUE TITLE
Source not available

### ISSUE THREAD

**Issue by k-takata** [vim-jp/vim-ci#12]
https://github.com/vim-jp/vim-ci/pull/11#issuecomment-47229584 より

> coveralls側で変更があったようで、Source not availableになっています。
> ref. lemurheavy/coveralls-public#263
> 
> おそらく cd せずにオプションでディレクトリを渡す必要があるのだと思います。

cd をしないようにした 18642c263ca3f28f6d986e54d7d143d33b6c989e のコミットは効果がなかったため、git submodule を使っていることが原因の可能性もあります。

**Comment by k-takata** [comment]
> 逆に、Switch Repo Source で参照先の repo を vim-jp/vim に切り替えてしまったらどうだろう？

今回試してみたところ、参照先は確かに vim-jp/vim に切り替わったのですが、coveralls のプロジェクト名も vim-jp/vim に切り替わってしまいました。しかもソースが見えないのはそのままだったようなので、元に戻しました。

git submodule を使っているのが原因だとすると、代わりに git subtree を使うとかですかね。

**Comment by koron** [comment]
メモ: subtree へ切り替わった場合は、vim-ciの更新をしているスクリプトも修正する必要がある

**Comment by k-takata** [comment]
ということで、git subtreeを使ってみるテスト。
https://github.com/vim-jp/vim-ci/tree/topic/use-git-subtree
coverallsの結果: https://coveralls.io/builds/3169706
ソースのディレクトリとして、`vim`を指定することでcoverallsでソースが見えるようになりました。

**Comment by k-takata** [comment]
操作手順のメモ

前準備:
```
git-subtree をインストール
git remote add vim-source https://github.com/vim-jp/vim.git
```

初回:
```
git rm -r vim
appveyor.yml から git submodule update の行を削除
git subtree add --prefix vim vim-source master --squash
```

次回以降
```
git fetch vim-source master
git subtree pull --prefix vim vim-source master --squash
```

参考: [Git Submodule の代替: Git Subtree - Atlassian Japan](http://japan.blogs.atlassian.com/2014/03/alternatives-to-git-submodule-git-subtree/ "Git Submodule の代替: Git Subtree - Atlassian Japan")

**Comment by k-takata** [comment]
> git subtree pull --prefix vim vim-source master --squash

`git subtree pull`, `git subtree merge`はデフォルトではコミットメッセージを入力するためにエディタが起動してしまうようなので、そうしないためには`-m`でコミットメッセージを指定が必要です。

**Comment by k-takata** [comment]
> そうしないためには-mでコミットメッセージを指定が必要です。

あるいは、環境変数`GIT_MERGE_AUTOEDIT`に`no`をセットしておけば、エディタが起動せずに自動でマージされます。

**Comment by koron** [comment]
ふとおもったんだけど、もう vim/vim に直接 .travis.yml 入れてもらったほうがええのとちゃう?

**Comment by k-takata** [comment]
確かに

**Comment by koron** [comment]
いままではマスターが mercurial だった & ただの mirror だから .travis.yml を独自に追加したくない、という苦肉の産物がこの vim-ci だったので、もし本家が github に移るならそこに .travis.yml を加えてもらうのが良さそう。

README.md はもう入っているのだし。

**Comment by crazymaster** [comment]
一応 appveyor.yml もですかね

**Comment by k-takata** [comment]
ci_run.sh は、.travis.yml に統合してしまいたい気がします。

**Comment by koron** [comment]
[Makefile](https://github.com/vim/vim/blob/master/Makefile) に travis-test みたいなターゲット追加しちゃったらどうです?

**Comment by k-takata** [comment]
[topic/merge-sh-to-ymlブランチ](https://github.com/vim-jp/vim-ci/tree/topic/merge-sh-to-yml)で実験中。
一応動いてそう。 https://travis-ci.org/vim-jp/vim-ci/builds/76287236

> Makefile に travis-test みたいなターゲット追加しちゃったらどうです?

まあ、それもありですかね? そこまでする必要もない気がしますが。

**Comment by k-takata** [comment]
https://github.com/vim/vim/pull/401

**Comment by koron** [comment]
deprecated.
