### ISSUE TITLE
Testing for patches

### ISSUE THREAD

**Issue by mattn** [vim-jp/vim-ci#21]
https://groups.google.com/forum/#!topic/vim_dev/S9nV1CWUMKQ

ブランチに `001.foo.patch` `002.bar.patch` といった名前でパッチが置かれている場合は適用してビルドとテストを実行する案が出てます。

**Comment by koron** [comment]
これだけ足せば良いかしら?

```
before_script:
  - find $TRAVIS_BUILD_DIR/patches -type f -not -path '*/\.*'
      -exec patch -p1 -d $TRAVIS_BUILD_DIR/vim-src -i {} \;
```

https://github.com/fwalch/vim-ci/blob/450c202916857bf08e6a8229ebffc680fa4eec33/.travis.yml#L28-L30

**Comment by koron** [comment]
なるほど。向こうは hg clone して回すタイプなのね。

**Comment by koron** [comment]
deprecated.
